audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: about
    url: http://www.teamfredasells.com/about-us/
client:
  name: Matt & Jenna Freda
  title:
  license_number:
  about_markdown: |
    Matt and Jenn Freda have a decade of experience in the real estate business, and are the leaders of a top-producing team in the Greater Orlando Area. In the past 3 years teamFREDA has sold over 500 homes! Their websites attract hundreds of thousands of views annually, and they have a database of over 9,000 buyers actively searching in the Greater Orlando Area.

    A normal real estate transaction has over 200 separate tasks that require a variety of skills. For the same price as working with a normal agent, working with Matt and Jenn ensures that you have a full team behind you, including buyer specialists, a marketing department, administrative assistants, and transaction coordinators, among others. With their team structure, technology, and systems in place, Matt and Jenn Freda have the experience and knowledge necessary to get your property sold for the most money in the least amount of time.
  market: Orlando
  brand: teamFREDA
  brokerage: Powered by eXp Realty
  address: 651 W. Warren Ave Longwood, FL 32750
  phone: 407-513-4724
  phone_type:
  phone2:
  phone2_type:
  email: info@teamFREDAsells.com
  url: http://teamFREDAsells.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.findorlandoareahouses.com/homevalue/Orlando
  second_CTA_text: Home Search
  second_CTA_URL: http://www.findorlandoareahouses.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.findorlandoareahouses.com/homevalue/Orlando

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.findorlandoareahouses.com/
    
third_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Join teamFREDA"
    CTA_text2: "Contact Us Today"
    CTA_link_text2: "Apply"
    CTA_url2: http://fredarealtyorlando.com/join-teamfreda/ 

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/teamFREDA/?fref=ts
  linkedin_url: https://www.linkedin.com/company/freda-realty-inc-?trk=cws-cpw-coname-0-0
  gplus_url: http://plus.google.com/115804475176857276722
  youtube_url: https://www.youtube.com/channel/UCR34kwpGnpy5s6brU9WHp7g
  twitter_url: https://twitter.com/FredaRealty
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/teamFREDA/
  trulia_url: https://www.trulia.com/profile/matthew-freda-agent-longwood-fl-zgqlnqtf/overview
  yelp_url: https://www.yelp.com/biz/matthew-j-freda-real-estate-callicoon
  podcast_url: https://itunes.apple.com/us/podcast/team-freda-greater-orlando-real-estate-podcast/id1039517219?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c49e31'
  theme_color: '#202020'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
